[package]
name    = "punch-core"
version = "0.9.2"
edition = "2021"
authors = ["Syed Mannan Saood <syed.mannan@outlook.com>"]
description = "Core library for Punch — p2p networking, file transfer, port forwarding"
license = "MIT"
repository = "https://github.com/MannanSaood/punch"

[lib]
name = "punch_core"
path = "src/lib.rs"

[dependencies]
tokio             = { version = "1",    features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
serde             = { version = "1",    features = ["derive"] }
serde_json        = "1"
chacha20poly1305  = "0.10"
anyhow            = "1"
dirs              = "5"
tracing           = "0.1"
rand              = "0.8"
uuid              = { version = "1", features = ["v4"] }
chrono            = { version = "0.4", features = ["serde"] }
futures-util      = "0.3"
futures           = "0.3"
url               = "2"
x25519-dalek      = { version = "2", features = ["static_secrets"] }
rand_core         = { version = "0.6", features = ["getrandom"] }
axum              = { version = "0.7", features = ["ws"] }
tower             = "0.4"
tower-http        = { version = "0.5", features = ["fs", "cors"] }
sha2              = "0.10"
indicatif         = "0.17"
iroh              = "0.96"
bytes             = "1"
portable-pty      = "0.8"
crossterm         = "0.27"
rust-embed        = "8.0"
mime_guess        = "2.0"